### ISSUE TITLE
DataParser Implementation

### ISSUE THREAD

**Issue by joshkimmel16** [joshkimmel16/scalable-clustering#8]

**Comment by joshkimmel16** [comment]
Quick question on this front.

How does the DataParser handle null values (say, in a particular row)? I think we're going to need a method to indicate this somehow as otherwise the Compare function will almost certainly fail (especially for numerical values that are casted before being compared). Thoughts? I ask because our input data set definitely has null values.

**Comment by bobbyjudd** [comment]
Good point.  What do you think about extending the Config/ConfigParser to support a field for NULL_DEFAULTS which would be a comma separated list where each value represents that respective column's default value? For example,
```
DATA_START=1
NUM_ATTRS=3
DATA_INDICES=0,1,2  
DATA_TYPES=DATA_STRING,DATA_INT,DATA_DOUBLE
CUTOFF_VALS=[j],[5,3,7],[1.7]
NULL_DEFAULTS=a,0,0.0
DATA_PATH=test.csv
THRESHOLD=1.67
REPORT_PATH=path_to_report.txt
```
Also add a getter in Config and call from DataParser, something like:
```
// Iterating csv rows
for (string[] row : csvDataSet)
    // Iterating values in row
    for (string value : row)
        if (value == null)
            dataPoint.rawData[index] = config.GetNullDefault(index);
        else
            dataPoint.rawData[index] = value;
```

**Comment by joshkimmel16** [comment]
Yeah, that's what I was thinking as well. Going to add two field:
``
NULL_ACTION=[OMIT/DEFAULT_VALS]
DEFAULT_VALS=[as you described above]
``
I'm thinking it might be good to give the user the option to just omit any rows with null values as it might not make sense to map them to a particular value. Note that in .csv files null values appear as empty strings.
